# Generated by Django 3.2.23 on 2024-03-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_table',
            old_name='dob',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='user_table',
            old_name='gender',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='qualification',
        ),
    ]
