# Generated by Django 3.2.23 on 2024-03-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_app', '0002_auto_20240330_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='age',
            field=models.CharField(max_length=20),
        ),
    ]
