# Generated by Django 3.2.23 on 2024-03-29 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ds_app', '0003_alter_user_table_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=500)),
                ('treatment', models.CharField(max_length=500)),
                ('preventive_measure', models.CharField(max_length=500)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ds_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=500)),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ds_app.disease')),
            ],
        ),
    ]
